name: workmanager_test
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  workmanager: ^0.5.1
  shared_preferences: ^2.0.18
  path_provider: ^2.0.13
  firebase_core: ^2.7.0
  cloud_firestore:
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
